delete from user_friends;
delete from film_likes;
delete from film_genres;
delete from film_directors;
delete from users;
delete from films;
delete from directors;
delete from reviews;
delete from review_reactions;