CREATE TABLE if not exists users (
    id int GENERATED BY DEFAULT AS IDENTITY,
    email varchar(30) NOT NULL,
    login varchar(30) NOT NULL,
    name varchar(30) NOT NULL,
    birthday date NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE if not exists films (
     id int GENERATED BY DEFAULT AS IDENTITY,
     name varchar(50) NOT NULL,
     description varchar(200),
     release_date date NOT NULL,
     duration int NOT NULL,
     rating varchar(5) NOT NULL,
     CONSTRAINT films_pk PRIMARY KEY (id)
);


CREATE TABLE if not exists genres (
     id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     name varchar(20) NOT NULL,
     CONSTRAINT genres_pk PRIMARY KEY (id)
);

CREATE TABLE if not exists film_genres (
     film_id int NOT NULL REFERENCES films(id) on delete cascade,
     genre_id int NOT NULL REFERENCES genres(id) on delete cascade,
     CONSTRAINT film_genres_pk PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE if not exists user_friends (
     user_id int NOT NULL REFERENCES users(id) on delete cascade,
     friend_id int NOT NULL REFERENCES users(id) on delete cascade,
--     status varchar(10) NOT NULL,
     CONSTRAINT user_friends_pk PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE if not exists film_likes (
     film_id int NOT NULL REFERENCES films(id) on delete cascade,
     user_id int NOT NULL REFERENCES users(id) on delete cascade,
--     is_active boolean NOT NULL default true,
     CONSTRAINT film_likes_pk PRIMARY KEY (film_id, user_id)
);